# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\Codes\Cafe Management system\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 608)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(970, 608))
        MainWindow.setStyleSheet("\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #242424;\n"
"    color: #fff;\n"
"    selection-background-color: #fff;\n"
"    selection-color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item \n"
"{\n"
"    background-color: transparent;\n"
"    border-left: 1px solid #003333;\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected \n"
"{\n"
"    background-color: #003333;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed \n"
"{\n"
"    background-color: #006666;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: #4a5157;\n"
"    border: 1px solid #4a5157;\n"
"    padding: 10px;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"    min-width: 200px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"       background-color: #242424;\n"
"    height: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: #003333;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton \n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    padding: 3px;\n"
"    margin-left: 1px;\n"
"}\n"
"\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    background-color: rgba(70,162,218,50%);\n"
"    border: 1px solid #46a2da;\n"
"    color: #000;\n"
"    \n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: #727272;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: #727272;\n"
"    border: 1px solid #222;\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: #4891b4;\n"
"    color: #fff;\n"
"    min-width: 80px;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::flat\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #606060;\n"
"    color: #959595;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: #54aad3;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: #2385b4;\n"
"    border: 1px solid #46a2da;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::checked\n"
"{\n"
"    background-color: #bd5355;\n"
"    border: 1px solid #bd5355;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #242424;\n"
"    color : #fff;\n"
"    border: 1px solid #1d1d1d;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPlainTExtEdit-----*/\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"    color : #fff;\n"
"    border: 1px solid #1d1d1d;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolBox-----*/\n"
"QToolBox\n"
"{\n"
"    background-color: transparent;\n"
"    border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBox::tab\n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBox::tab:hover\n"
"{\n"
"    background-color: #006d6d;\n"
"    border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    background-color: #4a5157;\n"
"    padding-left: 6px;\n"
"    color: #fff;\n"
"    height: 20px;\n"
"    border-radius: 4px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #fff;\n"
"    selection-background-color: #002b2b;\n"
"    selection-color: #fff;\n"
"    outline: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    background-color: #4a5157;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    border-radius: 4px;\n"
"    width: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QDoubleSpinBox & QCalendarWidget-----*/\n"
"QDoubleSpinBox,\n"
"QCalendarWidget QSpinBox \n"
"{\n"
"    background-color: #242424;\n"
"    color : #fff;\n"
"    border: 1px solid #1d1d1d;\n"
"    border-radius: 4px;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-button, \n"
"QCalendarWidget QSpinBox::up-button\n"
"{\n"
"    background-color: #4a5157;\n"
"    width: 16px; \n"
"    border-top-right-radius: 4px;\n"
"    border-width: 1px;\n"
"    border-color: #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-button:hover, \n"
"QCalendarWidget QSpinBox::up-button:hover\n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-button:pressed, \n"
"QCalendarWidget QSpinBox::up-button:pressed\n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::up-arrow,\n"
"QCalendarWidget QSpinBox::up-arrow\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-button, \n"
"QCalendarWidget QSpinBox::down-button\n"
"{\n"
"    background-color: #4a5157;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"    border-bottom-right-radius: 4px;\n"
"    border-color: #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-button:hover, \n"
"QCalendarWidget QSpinBox::down-button:hover\n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-button:pressed, \n"
"QCalendarWidget QSpinBox::down-button:pressed\n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QDoubleSpinBox::down-arrow,\n"
"QCalendarWidget QSpinBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"QGroupBox \n"
"{\n"
"    border: 1px solid;\n"
"    border-color: #1d1d1d;\n"
"    border-radius: 4px;\n"
"    margin-top: 23px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title  \n"
"{\n"
"    background-color: #002b2b;\n"
"    color: #fff;\n"
"    subcontrol-position: top left;\n"
"    subcontrol-origin: margin;\n"
"    padding: 5px;\n"
"    min-width: 100px;\n"
"    border: 1px solid #1d1d1d;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QHeaderView-----*/\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #4a5157;\n"
"    border: none;\n"
"    color: #fff;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(227, 227, 227, 255),stop:1 rgba(187, 187, 187, 255));\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 1px solid #003333;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(227, 227, 227, 255),stop:1 rgba(187, 187, 187, 255));\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCalendarWidget-----*/\n"
"QCalendarWidget QToolButton\n"
"{\n"
"      background-color: transparent;\n"
"      color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QToolButton::hover\n"
"{\n"
"    background-color: #006666;\n"
"    border: 1px solid #006666;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu \n"
"{\n"
"    width: 120px;\n"
"    left: 20px;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QWidget \n"
"{ \n"
"    alternate-background-color: #4a5157; \n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QAbstractItemView:enabled \n"
"{\n"
"    color: #fff;  \n"
"    background-color: #242424;  \n"
"    selection-background-color: #002b2b; \n"
"    selection-color: #fff; \n"
"\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QAbstractItemView:disabled \n"
"{ \n"
"    color: #404040; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeWidget-----*/\n"
"QTreeView\n"
"{\n"
"    show-decoration-selected: 0;\n"
"    alternate-background-color: transparent;\n"
"    background-color: transparent;\n"
"       border: none;\n"
"    color: #fff;\n"
"    font: 8pt;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    color:#fff;\n"
"    background-color: #002b2b;\n"
"    border-radius: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:!selected:hover\n"
"{\n"
"    background-color: #5e5e5e;\n"
"    border: none;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"{\n"
"    image: url(://tree-closed.png);\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"{\n"
"    image: url(://tree-open.png);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"QListView \n"
"{\n"
"    background-color: transparent;\n"
"    alternate-background-color: transparent;\n"
"    border : none;\n"
"    color: #fff;\n"
"    show-decoration-selected: 1; \n"
"    outline: 0;\n"
"       border: 1px solid #1d1d1d;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::disabled \n"
"{\n"
"    background-color: #656565;\n"
"    color: #1b1b1b;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item \n"
"{\n"
"    background-color: transparent;\n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected \n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #002b2b;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:!active \n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #002b2b;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:active \n"
"{\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #002b2b;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:hover {\n"
"    background-color: #5e5e5e;\n"
"    border: none;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    background-color: lightgray;\n"
"    border: 1px solid #000;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\");\n"
"    background-color: #002b2b;\n"
"    border: 1px solid #3a546e;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #46a2da; \n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton \n"
"{\n"
"    color: #fff;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover \n"
"{\n"
"    background-color: #d3d3d3;\n"
"    border: 2px solid #002b2b;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked \n"
"{\n"
"    border: 2px solid #52beff;\n"
"    border-radius: 6px;\n"
"    background-color: #002b2b;  \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:vertical \n"
"{\n"
"   border: none;\n"
"   width: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"   border: none;\n"
"   border-radius : 0px;\n"
"   background-color: #7a7a7a;\n"
"   min-height: 80px;\n"
"   width : 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical:pressed\n"
"{\n"
"   background-color: #5d5f60; \n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical \n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"   background-color: #222222;\n"
"    \n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal \n"
"{\n"
"   border: none;\n"
"   height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"   border: none;\n"
"   border-radius : 0px;\n"
"   background-color: #7a7a7a;\n"
"   min-height: 80px;\n"
"   height : 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal:pressed\n"
"{\n"
"   background-color: #5d5f60; \n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"   border: none;\n"
"   background: transparent;\n"
"   height: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover \n"
"{\n"
"   background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:pressed \n"
"{\n"
"   background-color: #3f3f3f;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:horizontal\n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:horizontal \n"
"{\n"
"   width: 0px;\n"
"   height: 0px;\n"
"   background: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"   background-color: #222222;\n"
"    \n"
"}\n"
"\n"
"\n"
"/*-----QProgressBar-----*/\n"
"QProgressBar\n"
"{\n"
"    border: 1px solid #1d1d1d;\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"    color: #fff;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #3b86ae;\n"
"    border-radius: 9px;\n"
"    margin: 0.5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QStatusBar-----*/\n"
"QStatusBar\n"
"{\n"
"    background-color: #4a5157;\n"
"    color: #ffffff;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSizeGrip-----*/\n"
"QSizeGrip \n"
"{\n"
"    background-color: image(\"./ressources/sizegrip.png\"); /*To replace*/\n"
"    border: none;\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 971, 51))
        self.label.setStyleSheet("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 24pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(3)
        self.label.setMidLineWidth(2)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 121, 41))
        self.label_2.setStyleSheet("font: 87 14pt \"Segoe UI Black\";")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(3)
        self.label_2.setMidLineWidth(2)
        self.label_2.setObjectName("label_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 110, 160, 740))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.roll_parata = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.roll_parata.setObjectName("roll_parata")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.roll_parata)
        self.samosa = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.samosa.setObjectName("samosa")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.samosa)
        self.Vburger = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.Vburger.setObjectName("Vburger")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Vburger)
        self.Cburger = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.Cburger.setObjectName("Cburger")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Cburger)
        self.Eburger = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.Eburger.setObjectName("Eburger")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Eburger)
        self.sandwich = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.sandwich.setObjectName("sandwich")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sandwich)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 310, 121, 41))
        self.label_9.setStyleSheet("font: 87 14pt \"Segoe UI Black\";")
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_9.setLineWidth(3)
        self.label_9.setMidLineWidth(2)
        self.label_9.setObjectName("label_9")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 360, 151, 740))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.Gtea = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        self.Gtea.setObjectName("Gtea")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Gtea)
        self.Mtea = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        self.Mtea.setObjectName("Mtea")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Mtea)
        self.coffee = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        self.coffee.setObjectName("coffee")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.coffee)
        self.Hmilk = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        self.Hmilk.setObjectName("Hmilk")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Hmilk)
        self.Bcoffee = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        self.Bcoffee.setObjectName("Bcoffee")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Bcoffee)
        self.Btea = QtWidgets.QTextEdit(self.formLayoutWidget_2)
        self.Btea.setObjectName("Btea")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Btea)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(270, 60, 81, 41))
        self.label_16.setStyleSheet("font: 87 14pt \"Segoe UI Black\";")
        self.label_16.setFrameShape(QtWidgets.QFrame.Box)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_16.setLineWidth(3)
        self.label_16.setMidLineWidth(2)
        self.label_16.setObjectName("label_16")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(250, 110, 131, 492))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_17.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.orng = QtWidgets.QTextEdit(self.formLayoutWidget_3)
        self.orng.setObjectName("orng")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.orng)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_18.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.Jmango = QtWidgets.QTextEdit(self.formLayoutWidget_3)
        self.Jmango.setObjectName("Jmango")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Jmango)
        self.apple = QtWidgets.QTextEdit(self.formLayoutWidget_3)
        self.apple.setObjectName("apple")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.apple)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_20.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.Papple = QtWidgets.QTextEdit(self.formLayoutWidget_3)
        self.Papple.setObjectName("Papple")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Papple)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_19.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_19.setObjectName("label_19")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(270, 250, 91, 51))
        self.label_21.setStyleSheet("font: 87 14pt \"Segoe UI Black\";")
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_21.setLineWidth(3)
        self.label_21.setMidLineWidth(2)
        self.label_21.setObjectName("label_21")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(260, 320, 121, 492))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_22.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.banana = QtWidgets.QTextEdit(self.formLayoutWidget_4)
        self.banana.setObjectName("banana")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.banana)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_23.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_23.setObjectName("label_23")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.Smango = QtWidgets.QTextEdit(self.formLayoutWidget_4)
        self.Smango.setObjectName("Smango")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Smango)
        self.almond = QtWidgets.QTextEdit(self.formLayoutWidget_4)
        self.almond.setObjectName("almond")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.almond)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_24.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.sb = QtWidgets.QTextEdit(self.formLayoutWidget_4)
        self.sb.setObjectName("sb")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sb)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_25.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(710, 60, 91, 51))
        self.label_26.setStyleSheet("font: 87 14pt \"Segoe UI Black\";")
        self.label_26.setFrameShape(QtWidgets.QFrame.Box)
        self.label_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_26.setLineWidth(3)
        self.label_26.setMidLineWidth(2)
        self.label_26.setObjectName("label_26")
        self.receipt = QtWidgets.QTextBrowser(self.centralwidget)
        self.receipt.setGeometry(QtCore.QRect(560, 120, 401, 391))
        self.receipt.setStyleSheet("QTextEdit te;\n"
"te.setHtml(\"<p style=\\\"text-align: left\\\">This paragraph is left aligned\"\n"
"           \"<p style=\\\"text-align: right\\\">This paragraph is right aligned\");")
        self.receipt.setObjectName("receipt")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(570, 460, 71, 41))
        self.label_27.setStyleSheet("font: 87 14pt \"Segoe UI Black\";")
        self.label_27.setFrameShape(QtWidgets.QFrame.Box)
        self.label_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_27.setLineWidth(3)
        self.label_27.setMidLineWidth(2)
        self.label_27.setObjectName("label_27")
        self.cost = QtWidgets.QTextBrowser(self.centralwidget)
        self.cost.setGeometry(QtCore.QRect(660, 460, 261, 41))
        self.cost.setObjectName("cost")
        self.print = QtWidgets.QPushButton(self.centralwidget)
        self.print.setGeometry(QtCore.QRect(570, 520, 91, 31))
        self.print.setObjectName("print")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(860, 520, 91, 31))
        self.reset.setObjectName("reset")
        self.gr = QtWidgets.QPushButton(self.centralwidget)
        self.gr.setGeometry(QtCore.QRect(710, 520, 101, 31))
        self.gr.setObjectName("gr")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 970, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "I Minnor Cafe"))
        self.label.setText(_translate("MainWindow", "                           Cafe Management System"))
        self.label_2.setText(_translate("MainWindow", "   Snacks"))
        self.label_3.setText(_translate("MainWindow", "Roll Parata"))
        self.label_4.setText(_translate("MainWindow", "Samosa"))
        self.label_5.setText(_translate("MainWindow", "Vegetable Burger"))
        self.label_6.setText(_translate("MainWindow", "Chiken Burger"))
        self.label_7.setText(_translate("MainWindow", "Egg Burger"))
        self.label_8.setText(_translate("MainWindow", "Sandwich"))
        self.roll_parata.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Hot Drinks"))
        self.label_10.setText(_translate("MainWindow", "Green Tea"))
        self.label_11.setText(_translate("MainWindow", "Milk Tea"))
        self.label_12.setText(_translate("MainWindow", "Coffee"))
        self.label_13.setText(_translate("MainWindow", "Hot Milk"))
        self.label_14.setText(_translate("MainWindow", "Black Coffee"))
        self.label_15.setText(_translate("MainWindow", "Black Tea"))
        self.Gtea.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "Juices"))
        self.label_17.setText(_translate("MainWindow", "Orange"))
        self.orng.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "Mango"))
        self.label_20.setText(_translate("MainWindow", "Pine Apple"))
        self.label_19.setText(_translate("MainWindow", "Apple"))
        self.label_21.setText(_translate("MainWindow", "Shakes"))
        self.label_22.setText(_translate("MainWindow", "Banana"))
        self.banana.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "Mango"))
        self.label_24.setText(_translate("MainWindow", "Strawberry"))
        self.label_25.setText(_translate("MainWindow", "Almond"))
        self.label_26.setText(_translate("MainWindow", "Receipt"))
        self.receipt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">QTextEdit te;te.setHtml(&quot;</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">This paragraph is left aligned&quot;           &quot;</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">This paragraph is right aligned&quot;);</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "Cost"))
        self.print.setText(_translate("MainWindow", "PRINT"))
        self.reset.setText(_translate("MainWindow", "RESET"))
        self.gr.setText(_translate("MainWindow", "Generate Receipt"))
